version: 2.1
jobs:

  # cloud - production
  builtwithforge-com-functions:
    executor: functions
    steps:
      - functions:
          project: forge-report-app

  builtwithforge-com-hosting:
    executor: hosting
    steps:
      - hosting:
          project: forge-report-app

executors:
      
  functions:
    docker:
      - image: cimg/node:18.16-browsers
    resource_class: large
    working_directory: ~/forge/standalone/functions

  hosting:
    docker:
      - image: cimg/node:18.16-browsers
    resource_class: large
    working_directory: ~/forge/standalone

commands:

  prepare:
    steps:
      - checkout:
          path: ~/forge

      - run:
          name: Setup environment
          command: |
            npm install --prefix=$HOME/.local yarn@berry -g
            yarn --version

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "~/forge/yarn.lock" }}
      - run: 
          name: Install dependencies
          command: |
            (cd ~/forge && yarn install --immutable)

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "~/forge/yarn.lock" }}
          paths:
            - ~/forge/.yarn/cache
            - ~/forge/.yarn/unplugged

  functions:
    parameters:
      project:
        type: string
    steps:
      - prepare

      - run:
          name: Deploy firebase functions
          command: yarn run firebase deploy -f --only functions --project << parameters.project >>

  hosting:
    parameters:
      project:
        type: string
    steps:
      - prepare
      
      - run:
          name: Deploy firebase hosting & database
          command: |
            export NODE_ENV=production
            yarn build
            yarn run firebase deploy -f --only hosting --project << parameters.project >>

workflows:
  deploy:
    jobs:
      # Cloud - Production
      - builtwithforge-com-functions:
          filters:
            branches:
              only: main
      - builtwithforge-com-hosting:
          requires:
            - builtwithforge-com-functions
          filters:
            branches:
              only: main
